version: '3.8'

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mysql-double-entry
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_PASSWORD
      MYSQL_DATABASE: double_entry_bookkeeping
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database_mount:/database_mount
