version: '3.8'

services:
  db-double-entry:
    image: mysql:8
    container_name: mysql-double-entry
    environment:
      MYSQL_ROOT_PASSWORD: password # This sets the root password
      MYSQL_DATABASE: double_entry_db # This creates the initial database
    ports:
      - "3306:3306"
    volumes:
      - ./database_mount:/var/lib/mysql
